name: info-gap
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - aiohttp=3.9.5
  - aiosignal=1.3.1
  - annotated-types=0.6.0
  - anyio=4.3.0
  - arxiv=1.4.8
  - attrs=23.2.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2024.2.2
  - certifi=2024.2.2
  - charset-normalizer=3.3.2
  - click=8.1.7
  - colorama=0.4.6
  - distro=1.9.0
  - docstring_parser=0.16
  - exceptiongroup=1.2.0
  - feedparser=6.0.11
  - filelock=3.14.0
  - frozenlist=1.4.1
  - fsspec=2024.3.1
  - h11=0.14.0
  - h2=4.1.0
  - hpack=4.0.0
  - httpcore=1.0.5
  - httpx=0.27.0
  - huggingface_hub=0.23.0
  - hyperframe=6.0.1
  - idna=3.7
  - importlib-metadata=7.1.0
  - instructor=1.2.6
  - jinja2=3.1.4
  - ld_impl_linux-64=2.40
  - libexpat=2.6.2
  - libffi=3.4.2
  - libgcc-ng=13.2.0
  - libgomp=13.2.0
  - libnsl=2.0.1
  - libsqlite=3.45.3
  - libstdcxx-ng=13.2.0
  - libuuid=2.38.1
  - libxcrypt=4.4.36
  - libzlib=1.2.13
  - litellm=1.36.4
  - markdown-it-py=3.0.0
  - markupsafe=2.1.5
  - mdurl=0.1.2
  - multidict=6.0.5
  - ncurses=6.5
  - openai=1.28.0
  - openssl=3.3.0
  - packaging=23.2
  - pip=24.0
  - pydantic=2.7.0
  - pydantic-core=2.18.1
  - pygments=2.18.0
  - pysocks=1.7.1
  - python=3.12.3
  - python-dotenv=1.0.1
  - python_abi=3.12
  - pyyaml=6.0.1
  - readline=8.2
  - regex=2024.5.10
  - requests=2.31.0
  - rich=13.7.1
  - setuptools=69.5.1
  - sgmllib3k=1.0.0
  - shellingham=1.5.4
  - sniffio=1.3.1
  - tenacity=8.3.0
  - tiktoken=0.5.2
  - tk=8.6.13
  - tokenizers=0.19.1
  - tqdm=4.66.4
  - typer=0.9.4
  - typing-extensions=4.11.0
  - typing_extensions=4.11.0
  - tzdata=2024a
  - urllib3=2.2.1
  - wheel=0.43.0
  - xz=5.2.6
  - yaml=0.2.5
  - yarl=1.9.4
  - zipp=3.17.0
